// GENERATED by tools/generate_cornell.py from the frozen cornell-box/1.0
// standard. DO NOT EDIT BY HAND and DO NOT TWEAK NUMBERS: this scene is
// the renderer's permanent laboratory (see benchmarks/cornell_box/README.md).
// M4 note: this codegen header is a stopgap until the scene/material
// abstraction can load benchmarks/cornell_box/scene.json directly.
#pragma once

#include <array>
#include <cstdint>

namespace cornell {

inline constexpr char kStandard[] = "cornell-box/1.0";
inline constexpr float kExposure = 1.0000f;

struct MeshDef { const char* file; const char* material; };
struct MaterialDef { float albedo[3]; float roughness; float metalness; };
struct MaterialEntry { const char* name; MaterialDef def; };
struct VariantDef { const char* name; const char* title;
                    std::uint32_t meshCount; const MeshDef* meshes;
                    std::uint32_t lightCount; };

// clang-format off
inline constexpr MaterialDef kMat_baffle {
    { 0.7250f, 0.7100f, 0.6800f }, 0.9000f, 0.0000f };
inline constexpr MaterialDef kMat_blockShort {
    { 0.7250f, 0.7100f, 0.6800f }, 0.9000f, 0.0000f };
inline constexpr MaterialDef kMat_blockTall {
    { 0.7250f, 0.7100f, 0.6800f }, 0.9000f, 0.0000f };
inline constexpr MaterialDef kMat_ceiling {
    { 0.7250f, 0.7100f, 0.6800f }, 0.9000f, 0.0000f };
inline constexpr MaterialDef kMat_floor {
    { 0.7250f, 0.7100f, 0.6800f }, 0.9000f, 0.0000f };
inline constexpr MaterialDef kMat_sphereDielectric {
    { 0.7500f, 0.7500f, 0.7500f }, 0.1800f, 0.0000f };
inline constexpr MaterialDef kMat_sphereGold {
    { 1.0000f, 0.7700f, 0.3400f }, 0.4500f, 1.0000f };
inline constexpr MaterialDef kMat_sphereMirror {
    { 0.9500f, 0.9600f, 0.9800f }, 0.0200f, 1.0000f };
inline constexpr MaterialDef kMat_wallBack {
    { 0.7250f, 0.7100f, 0.6800f }, 0.9000f, 0.0000f };
inline constexpr MaterialDef kMat_wallLeft {
    { 0.6300f, 0.0650f, 0.0500f }, 0.9000f, 0.0000f };
inline constexpr MaterialDef kMat_wallRight {
    { 0.1400f, 0.4500f, 0.0910f }, 0.9000f, 0.0000f };
// Name -> material lookup (walked once at load time).
inline constexpr MaterialEntry kMaterialTable[] = {
    { "baffle", { { 0.7250f, 0.7100f, 0.6800f }, 0.9000f, 0.0000f } },
    { "block_short", { { 0.7250f, 0.7100f, 0.6800f }, 0.9000f, 0.0000f } },
    { "block_tall", { { 0.7250f, 0.7100f, 0.6800f }, 0.9000f, 0.0000f } },
    { "ceiling", { { 0.7250f, 0.7100f, 0.6800f }, 0.9000f, 0.0000f } },
    { "floor", { { 0.7250f, 0.7100f, 0.6800f }, 0.9000f, 0.0000f } },
    { "sphere_dielectric", { { 0.7500f, 0.7500f, 0.7500f }, 0.1800f, 0.0000f } },
    { "sphere_gold", { { 1.0000f, 0.7700f, 0.3400f }, 0.4500f, 1.0000f } },
    { "sphere_mirror", { { 0.9500f, 0.9600f, 0.9800f }, 0.0200f, 1.0000f } },
    { "wall_back", { { 0.7250f, 0.7100f, 0.6800f }, 0.9000f, 0.0000f } },
    { "wall_left", { { 0.6300f, 0.0650f, 0.0500f }, 0.9000f, 0.0000f } },
    { "wall_right", { { 0.1400f, 0.4500f, 0.0910f }, 0.9000f, 0.0000f } },
};
inline constexpr std::uint32_t kMaterialCount = 11u;

// Emitter quad (unlit emissive draw) + reference radiance.
inline constexpr float kEmitterMin[3] = { -0.6500f, 5.4900f, -0.5250f };
inline constexpr float kEmitterMax[3] = { 0.6500f, 5.4900f, 0.5250f };
inline constexpr float kEmitterRadiance = 12.0000f;   // L_e, linear

// Camera (engine convention: yaw 0 looks down -Z).
inline constexpr float kCameraPosition[3] = { 0.0000f, 2.7500f, 8.3500f };
inline constexpr float kCameraYawRadians   = 0.000000f;
inline constexpr float kCameraPitchRadians = 0.000000f;
inline constexpr float kCameraFovYRadians  = 0.685914f;  // 39.3 degrees
inline constexpr float kCameraNear = 0.100f;
inline constexpr float kCameraFar  = 100.00f;

// Point-light grid: rasterizer approximation of the area emitter.
inline constexpr std::uint32_t kLightCount = 16u;
inline constexpr float kLightIntensity = 1.023750f;
inline constexpr std::array<float, 3 * 16u> kLightPositions { {
    -0.4875f, 5.4400f, -0.3938f,
    -0.4875f, 5.4400f, -0.1312f,
    -0.4875f, 5.4400f, 0.1312f,
    -0.4875f, 5.4400f, 0.3938f,
    -0.1625f, 5.4400f, -0.3938f,
    -0.1625f, 5.4400f, -0.1312f,
    -0.1625f, 5.4400f, 0.1312f,
    -0.1625f, 5.4400f, 0.3938f,
    0.1625f, 5.4400f, -0.3938f,
    0.1625f, 5.4400f, -0.1312f,
    0.1625f, 5.4400f, 0.1312f,
    0.1625f, 5.4400f, 0.3938f,
    0.4875f, 5.4400f, -0.3938f,
    0.4875f, 5.4400f, -0.1312f,
    0.4875f, 5.4400f, 0.1312f,
    0.4875f, 5.4400f, 0.3938f,
} };

// Pinned triangle counts (bench_tests fails if generation drifts).
inline constexpr std::uint32_t kTris_baffle = 12u;
inline constexpr std::uint32_t kTris_blockShort = 12u;
inline constexpr std::uint32_t kTris_blockTall = 12u;
inline constexpr std::uint32_t kTris_ceiling = 2u;
inline constexpr std::uint32_t kTris_ceilingEmitter = 2u;
inline constexpr std::uint32_t kTris_floor = 2u;
inline constexpr std::uint32_t kTris_sphereDielectric = 2976u;
inline constexpr std::uint32_t kTris_sphereGold = 2976u;
inline constexpr std::uint32_t kTris_sphereMirror = 2976u;
inline constexpr std::uint32_t kTris_wallBack = 2u;
inline constexpr std::uint32_t kTris_wallLeft = 2u;
inline constexpr std::uint32_t kTris_wallRight = 2u;

inline constexpr MeshDef kMeshes_cornell01[] = {
    { "floor.obj", "floor" },
    { "ceiling.obj", "ceiling" },
    { "wall_left.obj", "wall_left" },
    { "wall_right.obj", "wall_right" },
    { "wall_back.obj", "wall_back" },
    { "block_tall.obj", "block_tall" },
    { "block_short.obj", "block_short" },
    { "ceiling_emitter.obj", "ceiling_emitter" },
};
inline constexpr VariantDef kVariant_cornell01 {
    "cornell01", "CBox-01 baseline", 8u, kMeshes_cornell01, 16u };

inline constexpr MeshDef kMeshes_cornell02[] = {
    { "floor.obj", "floor" },
    { "ceiling.obj", "ceiling" },
    { "wall_left.obj", "wall_left" },
    { "wall_right.obj", "wall_right" },
    { "wall_back.obj", "wall_back" },
    { "block_tall.obj", "block_tall" },
    { "block_short.obj", "block_short" },
    { "sphere_mirror.obj", "sphere_mirror" },
    { "sphere_gold.obj", "sphere_gold" },
    { "sphere_dielectric.obj", "sphere_dielectric" },
    { "ceiling_emitter.obj", "ceiling_emitter" },
};
inline constexpr VariantDef kVariant_cornell02 {
    "cornell02", "CBox-02 reflective materials", 11u, kMeshes_cornell02, 16u };

inline constexpr MeshDef kMeshes_cornell03[] = {
    { "floor.obj", "floor" },
    { "ceiling.obj", "ceiling" },
    { "wall_left.obj", "wall_left" },
    { "wall_right.obj", "wall_right" },
    { "wall_back.obj", "wall_back" },
    { "block_tall.obj", "block_tall" },
    { "block_short.obj", "block_short" },
    { "baffle.obj", "baffle" },
    { "ceiling_emitter.obj", "ceiling_emitter" },
};
inline constexpr VariantDef kVariant_cornell03 {
    "cornell03", "CBox-03 indirect illumination", 9u, kMeshes_cornell03, 16u };

inline constexpr const VariantDef* kVariants[] = { &kVariant_cornell01, &kVariant_cornell02, &kVariant_cornell03 };
inline constexpr std::uint32_t kVariantCount = 3u;

} // namespace cornell
