#pragma once
// ---------------------------------------------------------------------------
// AreaLight (M5.0) -- the engine's first real area light object.
//
// The frozen Cornell standard's emitter is a 1.30 x 1.05 m horizontal
// ceiling patch at y = 5.49 emitting uniform radiance L_e = 12.0 downward.
// From M4 back it was *approximated* by a flux-preserving 4x4 point-light
// grid (I = A*L_e/N, scene.json derivation, pinned in bench_tests); the
// grid-vs-area discrepancy is a documented term of the measured similarity
// gap. M5.0 replaces the approximation in the transport itself: this header
// carries the object AND the CPU reference math for the exact area-light
// transport the sandbox shader implements (every function here mirrors the
// GLSL in sandbox/src/shaders.h line for line -- bench_tests pins the
// mirror against fixtures generated by scripts/check_area_model.py, the
// float64 brute-force validator).
//
// Transport model (all validated in scripts/check_area_model.py, section
// numbering below refers to that script):
//   diffuse  : K = -1/2 * sum_i gamma_i * (N . m_i) over the patch polygon's
//              edges (Arvo's differential-to-polygon form factor; exact --
//              section 1 matched brute force to 1e-9). E_diffuse = L_e * K,
//              split with the engine's ambient convention
//              kD = (1 - F_amb) * (1 - metalness).
//   visibility: the emitter rect polygon minus each occluder's BACKPROJECTED
//              region (the central projection of the occluder through the
//              receiver onto the emitter plane -- exact blocked set for
//              convex occluders, section 2/5). The subtraction uses the
//              first-outside-edge decomposition: each piece is one
//              Sutherland-Hodgman half-plane clip (area- and Arvo-exact for
//              any simple subject; zero-width bridge edges carry no area
//              and their edge contributions cancel exactly), so the union
//              over multiple blockers is EXACT -- no multiplicative
//              double-count (the naive product over-darkened a cbox03
//              overlap band by 18.4%, section 4).
//              Boxes: region = convex hull of the two height-cap footprints
//              projected through the receiver (the radial sweep of the
//              footprint between the cap magnifications -- exact, section
//              2). Spheres: region = section of the tangent cone
//              {angle(dir, C_hat) <= asin(R/d)}, sampled by 33 boundary
//              directions in direction space (robust at the receiver-
//              on-surface degeneracy where the tangent circle collapses),
//              sub-horizontal generators far-clamped at 50 m -- the floor
//              sphere + floor receiver case sits exactly on the parabolic
//              boundary; the 33-gon is inscribed in the conic, a
//              ONE-SIDED under-block of <= ~9% of the local fraction in the
//              transition band, 0 elsewhere (sections 3/5: end-to-end
//              <= 0.9% of K on the hardest frozen config).
//   specular : representative point (reflection ray intersected with the
//              emitter plane, clamped into the rect), GGX point evaluation
//              with radiance L_e * Omega * vis where Omega = the patch's
//              solid angle (Van Oosterom-Strackee, exact to 1e-5 vs Monte
//              Carlo, section 6) -- energy-consistent one-tap quadrature of
//              int brdf_s(omega) L cos(theta) domega.
//
// Exactness contract (same class as the heightfield's): convex, static
// occluders; receivers never inside an occluder. The bias guard skips a
// primitive whose top is within uShadowBias of the receiver -- a receiver
// standing on an occluder cannot self-shade, matching the heightfield
// march's own-column semantics.
// ---------------------------------------------------------------------------

#include <cmath>

namespace engine {
namespace arealight {

// Frozen standard (cornell_scene_gen.h); kept here as defaults so the CPU
// mirror and the tests never depend on the sandbox translation unit.
constexpr float kEmitterHalfX = 0.65f;    // 1.30 m / 2
constexpr float kEmitterHalfZ = 0.525f;   // 1.05 m / 2
constexpr float kEmitterY     = 5.49f;
constexpr float kEmitterLe    = 12.0f;
constexpr float kBias         = 0.01f;    // == sandbox kShadowBias
constexpr float kFarClamp     = 50.0f;    // sub-horizontal generator clamp (room is 5.5 m)
constexpr int   kSphereRing   = 32;       // boundary directions (+1 vertex sample)
constexpr int   kMaxPieceVerts = 28;      // per-piece vertex capacity
constexpr int   kMaxPieces     = 16;       // visible-region piece capacity

// A visible-region piece: a simple polygon on the emitter plane, tracked as
// (x, z) vertices. Pieces are disjoint; their union is the lit part.
struct Piece {
    float x[kMaxPieceVerts];
    float z[kMaxPieceVerts];
    int   n = 0;
};

struct OccluderBox {
    float x0, x1, z0, z1, ylo, yhi;
};
struct OccluderSphere {
    float cx, cy, cz, R;
};

inline float dot3(float ax, float ay, float az,
                  float bx, float by, float bz) {
    return ax * bx + ay * by + az * bz;
}

// ---------------------------------------------------------------------------
// Arvo differential-to-polygon form factor. K = -1/2 * sum gamma_i (N . m_i).
// Vertex order contract: (x0,z0), (x1,z0), (x1,z1), (x0,z1) and CCW pieces
// (Sutherland-Hodgman preserves subject orientation); the sign is pinned by
// scripts/check_area_model.py section 1 (1e-9 vs brute force).
// ---------------------------------------------------------------------------
inline float formFactorPoly(float px, float py, float pz,
                            float nx, float ny, float nz,
                            const float xs[], const float zs[], int n) {
    if (n < 3) {
        return 0.0f;
    }
    float sum = 0.0f;
    for (int i = 0; i < n; ++i) {
        const int j = (i + 1) % n;
        // unit directions from the receiver to vertices i and j
        const float ux = xs[i] - px, uy = kEmitterY - py, uz = zs[i] - pz;
        const float vx = xs[j] - px, vy = kEmitterY - py, vz = zs[j] - pz;
        const float ul = std::sqrt(ux * ux + uy * uy + uz * uz);
        const float vl = std::sqrt(vx * vx + vy * vy + vz * vz);
        if (ul < 1e-12f || vl < 1e-12f) {
            continue;
        }
        const float a[3] = { ux / ul, uy / ul, uz / ul };
        const float b[3] = { vx / vl, vy / vl, vz / vl };
        const float cr[3] = {
            a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0]
        };
        const float ln = std::sqrt(cr[0] * cr[0] + cr[1] * cr[1] + cr[2] * cr[2]);
        if (ln < 1e-12f) {
            continue;
        }
        float ca = a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
        if (ca > 1.0f)  ca = 1.0f;
        if (ca < -1.0f) ca = -1.0f;
        const float gamma = std::acos(ca);
        sum += gamma * (nx * cr[0] + ny * cr[1] + nz * cr[2]) / ln;
    }
    return -0.5f * sum;
}

// Rect form factor helper: the frozen winding (validated positive).
inline float formFactorRect(float px, float py, float pz,
                            float nx, float ny, float nz,
                            float centerX, float centerZ,
                            float halfX, float halfZ) {
    const float xs[4] = { centerX - halfX, centerX + halfX,
                          centerX + halfX, centerX - halfX };
    const float zs[4] = { centerZ - halfZ, centerZ - halfZ,
                          centerZ + halfZ, centerZ + halfZ };
    return formFactorPoly(px, py, pz, nx, ny, nz, xs, zs, 4);
}

// ---------------------------------------------------------------------------
// Van Oosterom-Strackee solid angle of the rect (fan of 2 triangles).
// Magnitude validated to ~1e-5 vs Monte Carlo; sign is winding -> abs().
// ---------------------------------------------------------------------------
inline float solidAngleRect(float px, float py, float pz,
                            float centerX, float centerZ,
                            float halfX, float halfZ) {
    float v[4][3];
    const float xs[4] = { centerX - halfX, centerX + halfX,
                          centerX + halfX, centerX - halfX };
    const float zs[4] = { centerZ - halfZ, centerZ - halfZ,
                          centerZ + halfZ, centerZ + halfZ };
    for (int i = 0; i < 4; ++i) {
        const float ux = xs[i] - px, uy = kEmitterY - py, uz = zs[i] - pz;
        const float ul = std::sqrt(ux * ux + uy * uy + uz * uz);
        v[i][0] = ux / ul; v[i][1] = uy / ul; v[i][2] = uz / ul;
    }
    float om = 0.0f;
    for (int k = 1; k <= 2; ++k) {
        const float* a = v[0];
        const float* b = v[k];
        const float* c = v[k + 1];
        const float cr[3] = {
            b[1] * c[2] - b[2] * c[1],
            b[2] * c[0] - b[0] * c[2],
            b[0] * c[1] - b[1] * c[0]
        };
        const float num = a[0] * cr[0] + a[1] * cr[1] + a[2] * cr[2];
        const float den = 1.0f + (a[0] * b[0] + a[1] * b[1] + a[2] * b[2])
                                + (b[0] * c[0] + b[1] * c[1] + b[2] * c[2])
                                + (c[0] * a[0] + c[1] * a[1] + c[2] * a[2]);
        om += 2.0f * std::atan2(num, den);
    }
    return std::fabs(om);
}

// ---------------------------------------------------------------------------
// 2D convex hull (monotone chain), insertion sort first. Mirrors the GLSL.
// Input pts[2*n] (x,z) pairs; output hull[2*m] CCW; returns m.
// ---------------------------------------------------------------------------
inline void hullSort(float* pts, int n) {
    // insertion sort by (x, z)
    for (int i = 1; i < n; ++i) {
        const float x = pts[2 * i], z = pts[2 * i + 1];
        int j = i - 1;
        while (j >= 0 && (pts[2 * j] > x ||
               (pts[2 * j] == x && pts[2 * j + 1] > z))) {
            pts[2 * (j + 1)]     = pts[2 * j];
            pts[2 * (j + 1) + 1] = pts[2 * j + 1];
            --j;
        }
        pts[2 * (j + 1)] = x;
        pts[2 * (j + 1) + 1] = z;
    }
}

inline int hull2d(const float* ptsIn, int n, float* hullOut) {
    if (n < 3) {
        for (int i = 0; i < n; ++i) {
            hullOut[2 * i] = ptsIn[2 * i];
            hullOut[2 * i + 1] = ptsIn[2 * i + 1];
        }
        return n;
    }
    float pts[2 * (kSphereRing + 1)];
    for (int i = 0; i < 2 * n; ++i) pts[i] = ptsIn[i];
    hullSort(pts, n);
    // dedupe
    int m = 0;
    float uniq[2 * (kSphereRing + 1)];
    for (int i = 0; i < n; ++i) {
        if (m == 0 || pts[2 * i] != uniq[2 * (m - 1)] ||
                      pts[2 * i + 1] != uniq[2 * (m - 1) + 1]) {
            uniq[2 * m] = pts[2 * i];
            uniq[2 * m + 1] = pts[2 * i + 1];
            ++m;
        }
    }
    if (m < 3) {
        for (int i = 0; i < m; ++i) {
            hullOut[2 * i] = uniq[2 * i];
            hullOut[2 * i + 1] = uniq[2 * i + 1];
        }
        return m;
    }
    int k = 0;
    float lower[2 * (kSphereRing + 1)];
    for (int i = 0; i < m; ++i) {
        const float px = uniq[2 * i], pz = uniq[2 * i + 1];
        while (k >= 2) {
            const float ox = lower[2 * (k - 2)], oz = lower[2 * (k - 2) + 1];
            const float ax = lower[2 * (k - 1)], az = lower[2 * (k - 1) + 1];
            const float cr = (ax - ox) * (pz - oz) - (az - oz) * (px - ox);
            if (cr <= 0.0f) { --k; } else { break; }
        }
        lower[2 * k] = px; lower[2 * k + 1] = pz; ++k;
    }
    int u = 0;
    float upper[2 * (kSphereRing + 1)];
    for (int i = m - 1; i >= 0; --i) {
        const float px = uniq[2 * i], pz = uniq[2 * i + 1];
        while (u >= 2) {
            const float ox = upper[2 * (u - 2)], oz = upper[2 * (u - 2) + 1];
            const float ax = upper[2 * (u - 1)], az = upper[2 * (u - 1) + 1];
            const float cr = (ax - ox) * (pz - oz) - (az - oz) * (px - ox);
            if (cr <= 0.0f) { --u; } else { break; }
        }
        upper[2 * u] = px; upper[2 * u + 1] = pz; ++u;
    }
    int h = 0;
    for (int i = 0; i < k - 1; ++i) {
        hullOut[2 * h] = lower[2 * i]; hullOut[2 * h + 1] = lower[2 * i + 1]; ++h;
    }
    for (int i = 0; i < u - 1; ++i) {
        hullOut[2 * h] = upper[2 * i]; hullOut[2 * h + 1] = upper[2 * i + 1]; ++h;
    }
    return h;
}

// ---------------------------------------------------------------------------
// One Sutherland-Hodgman pass against the line a->b, splitting the subject
// into (right, left). The hull interior is on the LEFT of each CCW hull
// edge, so 'right' = outside. Area- and form-factor-exact for any simple
// subject (bridges lie on the clip line, carry no area, and their Arvo
// spur contributions cancel).
// ---------------------------------------------------------------------------
inline void clipSplit(const Piece& poly,
                      float ax, float az, float bx, float bz,
                      Piece& rightOut, Piece& leftOut) {
    rightOut.n = 0;
    leftOut.n = 0;
    const float ex = bx - ax, ez = bz - az;
    for (int i = 0; i < poly.n; ++i) {
        const int j = (i + 1) % poly.n;
        const float px = poly.x[i], pz = poly.z[i];
        const float qx = poly.x[j], qz = poly.z[j];
        const float sp = ex * (pz - az) - ez * (px - ax);
        const float sq = ex * (qz - az) - ez * (qx - ax);
        const bool inP = sp <= 0.0f;   // right side = outside the hull
        const bool inQ = sq <= 0.0f;
        if (inP && rightOut.n < kMaxPieceVerts) {
            rightOut.x[rightOut.n] = px; rightOut.z[rightOut.n] = pz; ++rightOut.n;
        }
        if (!inP && leftOut.n < kMaxPieceVerts) {
            leftOut.x[leftOut.n] = px; leftOut.z[leftOut.n] = pz; ++leftOut.n;
        }
        if (inP != inQ) {
            const float t = sp / (sp - sq);
            const float cx = px + t * (qx - px);
            const float cz = pz + t * (qz - pz);
            if (rightOut.n < kMaxPieceVerts) {
                rightOut.x[rightOut.n] = cx; rightOut.z[rightOut.n] = cz; ++rightOut.n;
            }
            if (leftOut.n < kMaxPieceVerts) {
                leftOut.x[leftOut.n] = cx; leftOut.z[leftOut.n] = cz; ++leftOut.n;
            }
        }
    }
}

// First-outside-edge subtraction of a convex blocker polygon B from the
// piece list (see the header comment). Returns the new piece count.
inline int subtractBlocker(const Piece* pieces, int pieceCount,
                           const float* Bx, const float* Bz, int bn,
                           Piece* piecesOut) {
    int outCount = 0;
    for (int p = 0; p < pieceCount; ++p) {
        Piece W = pieces[p];
        for (int i = 0; i < bn && W.n >= 3; ++i) {
            const int j = (i + 1) % bn;
            Piece outside;
            Piece inside;
            clipSplit(W, Bx[i], Bz[i], Bx[j], Bz[j], outside, inside);
            if (outside.n >= 3 && outCount < kMaxPieces) {
                piecesOut[outCount++] = outside;
            }
            W = inside;
        }
        // W = piece n B: fully blocked, dropped
    }
    return outCount;
}

// Box blocker polygon: the convex hull of the two height-cap footprints
// projected through the receiver (the exact radial sweep; header comment).
// Returns the hull vertex count, 0 = skip (ineligible).
inline int boxBlocker(float px, float py, float pz,
                      const OccluderBox& box,
                      float* Bx, float* Bz) {
    float pts[2 * 8];
    const float ylo2 = (box.ylo > py + kBias) ? box.ylo : (py + kBias);
    const float yhi2 = (box.yhi < (kEmitterY - kBias)) ? box.yhi : (kEmitterY - kBias);
    if (ylo2 >= yhi2 || yhi2 <= py + kBias) {
        return 0;
    }
    const float mIn  = (kEmitterY - py) / (yhi2 - py);
    const float mOut = (kEmitterY - py) / (ylo2 - py);
    const float cx[4] = { box.x0, box.x1, box.x1, box.x0 };
    const float cz[4] = { box.z0, box.z0, box.z1, box.z1 };
    int n = 0;
    for (int c = 0; c < 4; ++c) {
        for (int mm = 0; mm < 2; ++mm) {
            const float m = (mm == 0) ? mIn : mOut;
            pts[2 * n]     = px + m * (cx[c] - px);
            pts[2 * n + 1] = pz + m * (cz[c] - pz);
            ++n;
        }
    }
    float hull[2 * 8];
    const int h = hull2d(pts, n, hull);
    for (int i = 0; i < h; ++i) {
        Bx[i] = hull[2 * i];
        Bz[i] = hull[2 * i + 1];
    }
    return h;
}

// Sphere blocker polygon: 33 boundary directions of the tangent cone,
// projected (sub-horizontal generators far-clamped). Returns the count.
inline int sphereBlocker(float px, float py, float pz,
                         const OccluderSphere& s,
                         float* Bx, float* Bz) {
    if (s.cy + s.R <= py + kBias) {
        return 0;   // sphere entirely below the receiver
    }
    const float gx = s.cx - px, gy = s.cy - py, gz = s.cz - pz;
    const float d = std::sqrt(gx * gx + gy * gy + gz * gz);
    if (d * d < (s.R - kBias) * (s.R - kBias)) {
        Bx[0] = -1e3f; Bz[0] = -1e3f;   // deep inside: caller treats as
        Bx[1] =  1e3f; Bz[1] = -1e3f;   // a full-block sentinel (not the
        Bx[2] =  0.0f; Bz[2] =  1e3f;   // frozen rig's contract)
        return 3;
    }
    const float chx = gx / d, chy = gy / d, chz = gz / d;
    float sa = s.R / d;
    if (sa > 1.0f) sa = 1.0f;
    const float ca = std::sqrt(1.0f - sa * sa);
    // orthonormal basis perpendicular to C_hat (stable pick)
    float e1x, e1y, e1z;
    if (std::fabs(chy) < 0.9f) {
        // e1 = normalize(C_hat x (0,1,0))
        e1x = chz; e1y = 0.0f; e1z = -chx;
    } else {
        // e1 = normalize(C_hat x (1,0,0))
        e1x = 0.0f; e1y = chz; e1z = -chy;
    }
    const float e1l = std::sqrt(e1x * e1x + e1y * e1y + e1z * e1z);
    e1x /= e1l; e1y /= e1l; e1z /= e1l;
    // e2 = C_hat x e1
    const float e2x = chy * e1z - chz * e1y;
    const float e2y = chz * e1x - chx * e1z;
    const float e2z = chx * e1y - chy * e1x;
    // ring directions + the max-elevation extremum (the conic vertex)
    float ct[kSphereRing + 1];
    float st[kSphereRing + 1];
    for (int k = 0; k < kSphereRing; ++k) {
        const float th = 6.28318530718f * static_cast<float>(k)
                       / static_cast<float>(kSphereRing);
        ct[k] = std::cos(th);
        st[k] = std::sin(th);
    }
    // extremum angle: theta_v = atan2(e2.y, e1.y) -- the ring's max-d.y
    // direction, i.e. the conic's vertex (the chord-error peak otherwise)
    {
        const float thv = std::atan2(e2y, e1y);
        ct[kSphereRing] = std::cos(thv);
        st[kSphereRing] = std::sin(thv);
    }
    float pts[2 * (kSphereRing + 1)];
    int n = 0;
    for (int k = 0; k <= kSphereRing; ++k) {
        const float dx = ca * chx + sa * (e1x * ct[k] + e2x * st[k]);
        const float dy = ca * chy + sa * (e1y * ct[k] + e2y * st[k]);
        const float dz = ca * chz + sa * (e1z * ct[k] + e2z * st[k]);
        if (dy > 1e-6f) {
            const float t = (kEmitterY - py) / dy;
            pts[2 * n]     = px + t * dx;
            pts[2 * n + 1] = pz + t * dz;
            ++n;
        } else {
            const float hxz = std::sqrt(dx * dx + dz * dz);
            if (hxz > 1e-9f) {
                pts[2 * n]     = px + kFarClamp * dx / hxz;
                pts[2 * n + 1] = pz + kFarClamp * dz / hxz;
                ++n;
            }
        }
    }
    if (n < 3) {
        return 0;
    }
    float hull[2 * (kSphereRing + 1)];
    const int h = hull2d(pts, n, hull);
    for (int i = 0; i < h; ++i) {
        Bx[i] = hull[2 * i];
        Bz[i] = hull[2 * i + 1];
    }
    return h;
}

// ---------------------------------------------------------------------------
// THE transport: visible-region form factor.
//   K_rect : the unshadowed rect form factor (also the denominator of the
//            scalar visibility ratio used by the specular term)
//   K_vis  : after subtracting every occluder's backprojected region
// Returns K_vis; K_rect is written through the out-param.
// ---------------------------------------------------------------------------
inline float visibleFormFactor(float px, float py, float pz,
                               float nx, float ny, float nz,
                               float centerX, float centerZ,
                               float halfX, float halfZ,
                               const OccluderBox* boxes, int boxCount,
                               const OccluderSphere* spheres, int sphereCount,
                               float& K_rect) {
    K_rect = formFactorRect(px, py, pz, nx, ny, nz, centerX, centerZ, halfX, halfZ);
    if (K_rect <= 0.0f) {
        return 0.0f;   // backfacing / below the emitter plane
    }
    Piece pieces[kMaxPieces];
    Piece init;
    init.n = 4;
    init.x[0] = centerX - halfX; init.z[0] = centerZ - halfZ;
    init.x[1] = centerX + halfX; init.z[1] = centerZ - halfZ;
    init.x[2] = centerX + halfX; init.z[2] = centerZ + halfZ;
    init.x[3] = centerX - halfX; init.z[3] = centerZ + halfZ;
    pieces[0] = init;
    int pieceCount = 1;

    float Bx[kSphereRing + 1];
    float Bz[kSphereRing + 1];
    for (int b = 0; b < boxCount; ++b) {
        const int h = boxBlocker(px, py, pz, boxes[b], Bx, Bz);
        if (h < 3) continue;
        Piece next[kMaxPieces];
        const int nc = subtractBlocker(pieces, pieceCount, Bx, Bz, h, next);
        for (int i = 0; i < nc; ++i) pieces[i] = next[i];
        pieceCount = nc;
        if (pieceCount == 0) return 0.0f;
    }
    for (int s = 0; s < sphereCount; ++s) {
        const int h = sphereBlocker(px, py, pz, spheres[s], Bx, Bz);
        if (h < 3) continue;
        Piece next[kMaxPieces];
        const int nc = subtractBlocker(pieces, pieceCount, Bx, Bz, h, next);
        for (int i = 0; i < nc; ++i) pieces[i] = next[i];
        pieceCount = nc;
        if (pieceCount == 0) return 0.0f;
    }

    float K = 0.0f;
    for (int p = 0; p < pieceCount; ++p) {
        K += formFactorPoly(px, py, pz, nx, ny, nz,
                            pieces[p].x, pieces[p].z, pieces[p].n);
    }
    if (K < 0.0f) K = 0.0f;
    if (K > K_rect) K = K_rect;   // visibility can only remove light
    return K;
}

} // namespace arealight
} // namespace engine
