# CMake generated Testfile for 
# Source directory: C:/Game project/engine
# Build directory: C:/Game project/build-vs2026-x64/engine
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(math_tests "C:/Game project/build-vs2026-x64/bin/Debug/engine_math_tests.exe")
  set_tests_properties(math_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;29;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(math_tests "C:/Game project/build-vs2026-x64/bin/Release/engine_math_tests.exe")
  set_tests_properties(math_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;29;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(math_tests "C:/Game project/build-vs2026-x64/bin/MinSizeRel/engine_math_tests.exe")
  set_tests_properties(math_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;29;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(math_tests "C:/Game project/build-vs2026-x64/bin/RelWithDebInfo/engine_math_tests.exe")
  set_tests_properties(math_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;29;add_test;C:/Game project/engine/CMakeLists.txt;0;")
else()
  add_test(math_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(frustum_tests "C:/Game project/build-vs2026-x64/bin/Debug/engine_frustum_tests.exe")
  set_tests_properties(frustum_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;40;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(frustum_tests "C:/Game project/build-vs2026-x64/bin/Release/engine_frustum_tests.exe")
  set_tests_properties(frustum_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;40;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(frustum_tests "C:/Game project/build-vs2026-x64/bin/MinSizeRel/engine_frustum_tests.exe")
  set_tests_properties(frustum_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;40;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(frustum_tests "C:/Game project/build-vs2026-x64/bin/RelWithDebInfo/engine_frustum_tests.exe")
  set_tests_properties(frustum_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;40;add_test;C:/Game project/engine/CMakeLists.txt;0;")
else()
  add_test(frustum_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(obj_tests "C:/Game project/build-vs2026-x64/bin/Debug/engine_obj_tests.exe")
  set_tests_properties(obj_tests PROPERTIES  WORKING_DIRECTORY "C:/Game project/engine/tests" _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;49;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(obj_tests "C:/Game project/build-vs2026-x64/bin/Release/engine_obj_tests.exe")
  set_tests_properties(obj_tests PROPERTIES  WORKING_DIRECTORY "C:/Game project/engine/tests" _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;49;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(obj_tests "C:/Game project/build-vs2026-x64/bin/MinSizeRel/engine_obj_tests.exe")
  set_tests_properties(obj_tests PROPERTIES  WORKING_DIRECTORY "C:/Game project/engine/tests" _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;49;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(obj_tests "C:/Game project/build-vs2026-x64/bin/RelWithDebInfo/engine_obj_tests.exe")
  set_tests_properties(obj_tests PROPERTIES  WORKING_DIRECTORY "C:/Game project/engine/tests" _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;49;add_test;C:/Game project/engine/CMakeLists.txt;0;")
else()
  add_test(obj_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(brdf_tests "C:/Game project/build-vs2026-x64/bin/Debug/engine_brdf_tests.exe")
  set_tests_properties(brdf_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;60;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(brdf_tests "C:/Game project/build-vs2026-x64/bin/Release/engine_brdf_tests.exe")
  set_tests_properties(brdf_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;60;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(brdf_tests "C:/Game project/build-vs2026-x64/bin/MinSizeRel/engine_brdf_tests.exe")
  set_tests_properties(brdf_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;60;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(brdf_tests "C:/Game project/build-vs2026-x64/bin/RelWithDebInfo/engine_brdf_tests.exe")
  set_tests_properties(brdf_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;60;add_test;C:/Game project/engine/CMakeLists.txt;0;")
else()
  add_test(brdf_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bench_tests "C:/Game project/build-vs2026-x64/bin/Debug/engine_bench_tests.exe")
  set_tests_properties(bench_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;74;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bench_tests "C:/Game project/build-vs2026-x64/bin/Release/engine_bench_tests.exe")
  set_tests_properties(bench_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;74;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bench_tests "C:/Game project/build-vs2026-x64/bin/MinSizeRel/engine_bench_tests.exe")
  set_tests_properties(bench_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;74;add_test;C:/Game project/engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bench_tests "C:/Game project/build-vs2026-x64/bin/RelWithDebInfo/engine_bench_tests.exe")
  set_tests_properties(bench_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Game project/engine/CMakeLists.txt;74;add_test;C:/Game project/engine/CMakeLists.txt;0;")
else()
  add_test(bench_tests NOT_AVAILABLE)
endif()
