#!/usr/bin/env python3
"""
generate_models.py -- regenerates the bundled OBJ assets for the M3 sandbox.

All models are emitted with:
  - `v` positions and `vn` normals
  - triangulated `f` faces in `v//vn` form
  - no material files: PBR materials are assigned per model in sandbox/main.cpp

Deterministic output (parametric math, fixed seeds) so regenerated assets are
reproducible. Usage:

    python3 tools/generate_models.py [output_dir]

Default output_dir: sandbox/assets/models (relative to the project root).
"""

import math
import os
import sys

MODELS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          "..", "sandbox", "assets", "models")


# ---------------------------------------------------------------------------
# OBJ emission
# ---------------------------------------------------------------------------

class ObjBuilder:
    """Accumulates triangles, deduplicates (position, normal) corners, and
    writes a Wavefront OBJ with `v//vn` faces."""

    def __init__(self):
        self.positions = []          # (x, y, z)
        self.normals = []            # (x, y, z)
        self.triangles = []          # ((vi, ni), (vi, ni), (vi, ni))
        self._cache = {}             # (pos, nrm) -> 0-based corner id

    def _corner(self, position, normal):
        key = (position, normal)
        if key not in self._cache:
            self._cache[key] = (len(self.positions), len(self.normals))
            self.positions.append(position)
            self.normals.append(normal)
        return self._cache[key]

    def add_triangle(self, a, b, c, na, nb, nc):
        # Safety net: never emit zero-area triangles (UV poles, repeated
        # corners). Mirrors the degeneracy rejection the C++ loader applies.
        ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
        vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
        crx, cry, crz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
        if crx * crx + cry * cry + crz * crz < 1e-16:
            return
        pa = self._corner(a, na)
        pb = self._corner(b, nb)
        pc = self._corner(c, nc)
        self.triangles.append((pa, pb, pc))

    def add_outward_triangle(self, a, b, c, na, nb, nc):
        """Adds a triangle, flipping the winding if needed so the geometric
        face normal agrees with the supplied vertex normals. Winding bugs are
        impossible to see in a text editor -- this makes them impossible to
        ship, too."""
        g = _fnorm(a, b, c)
        avg = (na[0] + nb[0] + nc[0], na[1] + nb[1] + nc[1], na[2] + nb[2] + nc[2])
        if g[0] * avg[0] + g[1] * avg[1] + g[2] * avg[2] < 0.0:
            b, c = c, b
            nb, nc = nc, nb
        self.add_triangle(a, b, c, na, nb, nc)

    def add_outward_flat_quad(self, a, b, c, d):
        """Adds a two-sided flat quad (for zero-thickness fins): both windings,
        same face normal."""
        n = _fnorm(a, b, c)
        self.add_triangle(a, b, c, n, n, n)
        self.add_triangle(a, c, d, n, n, n)
        self.add_triangle(d, c, b, n, n, n)
        self.add_triangle(d, b, a, n, n, n)

    def vertex_count(self):
        return len(self.positions)

    def triangle_count(self):
        return len(self.triangles)

    def write(self, path):
        with open(path, "w") as f:
            f.write("# Generated by tools/generate_models.py -- do not edit by hand.\n")
            f.write("# Deterministic output; regenerate with: python3 tools/generate_models.py\n")
            for p in self.positions:
                f.write("v %.6f %.6f %.6f\n" % p)
            for n in self.normals:
                f.write("vn %.6f %.6f %.6f\n" % n)
            for (a, b, c) in self.triangles:
                f.write("f %d//%d %d//%d %d//%d\n" % (
                    a[0] + 1, a[1] + 1,
                    b[0] + 1, b[1] + 1,
                    c[0] + 1, c[1] + 1))


def _fnorm(a, b, c):
    """Geometric normal from three vertices in winding order."""
    ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
    vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
    nx, ny, nz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
    l = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
    return (nx / l, ny / l, nz / l)


# ---------------------------------------------------------------------------
# Model: UV torus (smooth normals) -- metallic specular showcase
# ---------------------------------------------------------------------------

def build_torus(builder, R=0.72, r=0.30, seg_u=48, seg_v=24):
    def point(u, v):
        cu, su = math.cos(u), math.sin(u)
        cv, sv = math.cos(v), math.sin(v)
        return ((R + r * cv) * cu, r * sv, (R + r * cv) * su)

    def normal(u, v):
        cu, su = math.cos(u), math.sin(u)
        cv, sv = math.cos(v), math.sin(v)
        return (cv * cu, sv, cv * su)

    for i in range(seg_u):
        u0 = 2 * math.pi * i / seg_u
        u1 = 2 * math.pi * (i + 1) / seg_u
        for j in range(seg_v):
            v0 = 2 * math.pi * j / seg_v
            v1 = 2 * math.pi * (j + 1) / seg_v

            p00, p10, p01, p11 = point(u0, v0), point(u1, v0), point(u0, v1), point(u1, v1)
            n00, n10 = normal(u0, v0), normal(u1, v0)
            n01, n11 = normal(u0, v1), normal(u1, v1)

            builder.add_outward_triangle(p00, p10, p11, n00, n10, n11)
            builder.add_outward_triangle(p00, p11, p01, n00, n11, n01)


# ---------------------------------------------------------------------------
# Model: UV sphere (smooth normals) -- the classic specular-highlight test
# ---------------------------------------------------------------------------

def build_sphere(builder, radius=0.6, slices=48, stacks=32):
    def point(s, p):
        phi = math.pi * s / stacks
        theta = 2 * math.pi * p / slices
        n = (math.sin(phi) * math.cos(theta), math.cos(phi),
             math.sin(phi) * math.sin(theta))
        return (radius * n[0], radius * n[1], radius * n[2]), n

    for s in range(stacks):
        for p in range(slices):
            p00, n00 = point(s, p)
            p10, n10 = point(s, p + 1)
            p01, n01 = point(s + 1, p)
            p11, n11 = point(s + 1, p + 1)
            # At the poles the quad collapses: p00==p10 (s=0) or p01==p11
            # (s=stacks-1). ObjBuilder drops the zero-area triangle.
            builder.add_outward_triangle(p00, p01, p11, n00, n01, n11)
            builder.add_outward_triangle(p00, p11, p10, n00, n11, n10)


# ---------------------------------------------------------------------------
# Model: perturbed icosphere (flat normals) -- rough dielectric material demo
# ---------------------------------------------------------------------------

def _icosa_mesh():
    """Unit icosahedron with outward-oriented triangles (12 verts, 20 faces)."""
    phi = (1.0 + math.sqrt(5.0)) / 2.0
    raw = []
    for a, b in ((-1, phi), (1, phi), (-1, -phi), (1, -phi)):
        raw += [(0, a, b), (a, b, 0), (b, 0, a)]
    verts = []
    for v in raw:
        l = math.sqrt(sum(c * c for c in v))
        verts.append(tuple(c / l for c in v))

    def dist(a, b):
        return math.sqrt(sum((a[i] - b[i]) ** 2 for i in range(3)))

    min_edge = min(dist(verts[i], verts[j]) for i in range(12) for j in range(i + 1, 12))
    adj = {i: set() for i in range(12)}
    for i in range(12):
        for j in range(i + 1, 12):
            if dist(verts[i], verts[j]) < min_edge * 1.01:
                adj[i].add(j)
                adj[j].add(i)

    faces = set()
    for a in range(12):
        for b in adj[a]:
            for c in adj[a] & adj[b]:
                faces.add(tuple(sorted((a, b, c))))
    assert len(faces) == 20, "icosahedron must have exactly 20 faces"

    oriented = []
    for a, b, c in sorted(faces):
        pa, pb, pc = verts[a], verts[b], verts[c]
        n = _fnorm(pa, pb, pc)
        if n[0] * pa[0] + n[1] * pa[1] + n[2] * pa[2] > 0.0:
            oriented.append((a, b, c))
        else:
            oriented.append((a, c, b))
    return verts, oriented


def build_rock(builder, radius=0.62, subdivisions=2, seed=7):
    verts, faces = _icosa_mesh()

    for _ in range(subdivisions):
        midpoint_cache = {}
        new_faces = []

        def midpoint(a, b):
            key = (min(a, b), max(a, b))
            if key not in midpoint_cache:
                va, vb = verts[a], verts[b]
                m = tuple((va[i] + vb[i]) / 2.0 for i in range(3))
                l = math.sqrt(sum(c * c for c in m)) or 1.0
                midpoint_cache[key] = len(verts)
                verts.append(tuple(c / l for c in m))
            return midpoint_cache[key]

        for a, b, c in faces:
            ab, bc, ca = midpoint(a, b), midpoint(b, c), midpoint(c, a)
            new_faces += [(a, ab, ca), (ab, b, bc), (ca, bc, c), (ab, bc, ca)]
        faces = new_faces

    # Deterministic radial perturbation: layered trig "noise", no RNG drift.
    def bump(p):
        x, y, z = p
        d = (0.16 * math.sin(3.1 * x + 1.7 * z + seed)
             + 0.11 * math.sin(5.3 * y + 2.9 * x - seed)
             + 0.07 * math.sin(8.7 * z - 4.1 * y + 0.5 * seed))
        l = math.sqrt(x * x + y * y + z * z) or 1.0
        s = (radius + d) / l
        return (x * s, y * s, z * s)

    bumped = [bump(v) for v in verts]
    for a, b, c in faces:
        pa, pb, pc = bumped[a], bumped[b], bumped[c]
        n = _fnorm(pa, pb, pc)
        builder.add_triangle(pa, pb, pc, n, n, n)   # flat shading


# ---------------------------------------------------------------------------
# Model: low-poly spaceship (flat normals) -- hard-surface test for import
# ---------------------------------------------------------------------------

def build_ship(builder, sides=10):
    """Retro rocket built from tapered ring sections + three fins. Nose is +Y."""

    def ring(y, r):
        return [(r * math.cos(2 * math.pi * i / sides), y,
                 r * math.sin(2 * math.pi * i / sides)) for i in range(sides)]

    def band(y0, r0, y1, r1):
        """Surface-of-revolution band between two rings, wound outward."""
        low, high = ring(y0, r0), ring(y1, r1)
        for i in range(sides):
            j = (i + 1) % sides
            a, b, c, d = low[i], high[i], high[j], low[j]
            n = _fnorm(a, b, c)
            radial = (a[0], 0.0, a[2])
            if n[0] * radial[0] + n[2] * radial[2] < 0.0:
                a, b, c, d = d, c, b, a
            n = _fnorm(a, b, c)
            builder.add_triangle(a, b, c, n, n, n)
            builder.add_triangle(a, c, d, n, n, n)

    def cap(y, r, outward):
        """Cone cap: outward=+1 apex above the ring (nose), -1 below (tail)."""
        apex = (0.0, y, 0.0)
        base = ring(y - 0.12 * outward, r)
        for i in range(sides):
            j = (i + 1) % sides
            a, b = base[i], base[j]
            if outward > 0:
                n = _fnorm(apex, b, a)
                builder.add_triangle(apex, b, a, n, n, n)
            else:
                n = _fnorm(apex, a, b)
                builder.add_triangle(apex, a, b, n, n, n)

    # Fuselage: nose -> body -> tail.
    cap(0.95, 0.16, +1.0)          # nose cone (tip at +Y)
    band(0.83, 0.16, 0.45, 0.34)   # nose taper
    band(0.45, 0.34, -0.35, 0.36)  # main hull
    band(-0.35, 0.36, -0.62, 0.24) # tail taper
    cap(-0.62, 0.24, -1.0)         # engine end

    # Engine nozzle: flare then rim.
    band(-0.62, 0.24, -0.78, 0.30)
    band(-0.78, 0.30, -0.80, 0.22)

    # Fins: three thin swept blades, 120 degrees apart, double-sided.
    for k in range(3):
        ang = 2 * math.pi * k / 3
        ca, sa = math.cos(ang), math.sin(ang)
        px, pz = 0.30 * ca, 0.30 * sa   # root anchored on the hull surface

        def fp(dy, spread, thick=0.035):
            ox, oz = spread * ca, spread * sa
            tx, tz = -sa * thick / 2, ca * thick / 2
            return (px + ox + tx, -0.15 + dy, pz + oz + tz)

        a = fp(0.00, 0.10)   # root front
        b = fp(0.00, 0.78)   # tip front
        c = fp(0.42, 0.88)   # tip back
        d = fp(0.55, 0.16)   # root back
        builder.add_outward_flat_quad(a, b, c, d)


# ---------------------------------------------------------------------------

def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.normpath(MODELS_DIR)
    os.makedirs(out_dir, exist_ok=True)

    jobs = [
        ("torus.obj",  build_torus),
        ("sphere.obj", build_sphere),
        ("rock.obj",   build_rock),
        ("ship.obj",   build_ship),
    ]

    for filename, builder_fn in jobs:
        builder = ObjBuilder()
        builder_fn(builder)
        path = os.path.join(out_dir, filename)
        builder.write(path)
        print("%-12s %5d vertices, %5d triangles  ->  %s"
              % (filename, builder.vertex_count(), builder.triangle_count(), path))


if __name__ == "__main__":
    main()
